[tool.poetry]
name = "pymockserver"
version = "1.6.5"
description = "Simple MockServer implemented in python"
authors = ["Kudlaty <kfuks2@gmail.com>"]
license = "GPL-3.0"

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.6.5"
version_files = [
    "pyproject.toml:version",
    "pymockserver/main.py:__version__",
    "helm_v2/pymockserver/Chart.yaml:version",
    "helm_v2/pymockserver/values.yaml:tag",
    "helm_v3/pymockserver/Chart.yaml:version",
    "helm_v3/pymockserver/Chart.yaml:appVersion",
    "clients/typescript-node/package.json:version",
]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.61.1"
uvicorn = "^0.12.2"
email-validator = "^1.1.1"
diskcache = "^5.0.3"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.4"
mypy = "^0.790"
pre-commit = "^2.8.2"
pytest = "^6.1.2"
requests = "^2.24.0"
invoke = "^1.4.1"
gitpython = "^3.1.11"
mergedeep = "^1.3.0"
commitizen = "^2.6.0"
isort = "^5.6.4"

[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
