[tool.poetry]
name = "pymockserver"
version = "1.6.1"
description = "Simple MockServer implemented in python"
authors = ["Kudlaty <kfuks2@gmail.com>"]
license = "GPL-3.0"

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.6.1"
version_files = [
    "pyproject.toml:version",
    "pymockserver/main.py:__version__",
    "helm_v2/pymockserver/Chart.yaml:version",
    "helm_v2/pymockserver/values.yaml:tag",
    "helm_v3/pymockserver/Chart.yaml:version",
    "helm_v3/pymockserver/Chart.yaml:appVersion",
    "clients/typescript-node/package.json:version",
]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.46.0"
uvicorn = "^0.11.1"
email-validator = "^1.0.5"
diskcache = "^4.1.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
mypy = "^0.770"
flake8-mypy = "^17.8.0"
pre-commit = "^2.3.0"
pytest = "^5.4.1"
requests = "^2.23.0"
invoke = "^1.4.1"
gitpython = "^3.1.1"
mergedeep = "^1.3.0"
commitizen = "^1.20.0"

[tool.black]
line-length = 120
target-version = ['py37', 'py38']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
