[tool.poetry]
name = "pymockserver"
version = "1.6.4"
description = "Simple MockServer implemented in python"
authors = ["Kudlaty <kfuks2@gmail.com>"]
license = "GPL-3.0"

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.6.4"
version_files = [
    "pyproject.toml:version",
    "pymockserver/main.py:__version__",
    "helm_v2/pymockserver/Chart.yaml:version",
    "helm_v2/pymockserver/values.yaml:tag",
    "helm_v3/pymockserver/Chart.yaml:version",
    "helm_v3/pymockserver/Chart.yaml:appVersion",
    "clients/typescript-node/package.json:version",
]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.54.1"
uvicorn = "^0.11.1"
email-validator = "^1.0.5"
diskcache = "^4.1.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.1"
mypy = "^0.770"
pre-commit = "^2.4.0"
pytest = "^5.4.2"
requests = "^2.23.0"
invoke = "^1.4.1"
gitpython = "^3.1.2"
mergedeep = "^1.3.0"
commitizen = "^1.22.0"
isort = "^4.3.21"

[tool.black]
line-length = 120
target-version = ['py38']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
line_length = 120

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
