{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pymockserver.serviceAccountName" . }}
  labels:
{{ include "pymockserver.labels" . | nindent 4 }}
{{- end -}}
