apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-files
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ template "pymockserver.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $val := .Values.fixtureFiles }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
