{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pymockserver.serviceAccountName" . }}
  labels:
{{ include "pymockserver.labels" . | indent 4 }}
{{- end -}}
