#!/bin/sh -e

export PREFIX="poetry run python -m "
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

${PREFIX}isort --recursive --apply pymockserver tests
${PREFIX}black pymockserver tests
