#!/bin/sh -e

export PREFIX="poetry run python -m "
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

${PREFIX}pytest -vv tests/
${PREFIX}black pymockserver tests deploy --check
${PREFIX}isort --recursive --check-only pymockserver tests deploy
${PREFIX}flake8 pymockserver/ tests/ deploy/
${PREFIX}mypy pymockserver/ tests/ deploy/
