/**
 * MockServer API
 * Simple and fast mock server implemented in python
 *
 * The version of the OpenAPI document: 1.3.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class HttpResponse {
    /**
    * Status code of mocked response
    */
    'statusCode'?: number;
    /**
    * Headers included in mock response
    */
    'headers'?: { [key: string]: string; };
    /**
    * Body that will be returned
    */
    'body'?: string | object;
    /**
    * Number of times this mock will be returned until deleted. -1 means unlimited
    */
    'remainingTimes'?: number;
    /**
    * How much milliseconds wait until response
    */
    'delay'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "number"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string | object"
        },
        {
            "name": "remainingTimes",
            "baseName": "remainingTimes",
            "type": "number"
        },
        {
            "name": "delay",
            "baseName": "delay",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return HttpResponse.attributeTypeMap;
    }
}

