/**
 * MockServer API
 * Simple and fast mock server implemented in python
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";
import { MatchEnum } from "./matchEnum";

export class HttpRequest {
  /**
   * Http method
   */
  "method"?: string;
  /**
   * Url path
   */
  "path": string;
  /**
   * Query string parameters
   */
  "queryStringParameters"?: { [key: string]: Array<string> };
  /**
   * Headers that would match in request
   */
  "headers"?: { [key: string]: string };
  /**
   * Body that will be matched against request
   */
  "body"?: boolean | string | number | object | Array<object>;
  /**
   * Specify mode with witch body will be matched in request
   */
  "matchBodyMode"?: MatchEnum;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "method",
      baseName: "method",
      type: "string",
    },
    {
      name: "path",
      baseName: "path",
      type: "string",
    },
    {
      name: "queryStringParameters",
      baseName: "queryStringParameters",
      type: "{ [key: string]: Array<string>; }",
    },
    {
      name: "headers",
      baseName: "headers",
      type: "{ [key: string]: string; }",
    },
    {
      name: "body",
      baseName: "body",
      type: "boolean | string | number | object | Array<object>",
    },
    {
      name: "matchBodyMode",
      baseName: "match_body_mode",
      type: "MatchEnum",
    },
  ];

  static getAttributeTypeMap() {
    return HttpRequest.attributeTypeMap;
  }
}
