/**
 * MockServer API
 * Simple and fast mock server implemented in python
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";
import { ValidationError } from "./validationError";

export class HTTPValidationError {
  "detail"?: Array<ValidationError>;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "detail",
      baseName: "detail",
      type: "Array<ValidationError>",
    },
  ];

  static getAttributeTypeMap() {
    return HTTPValidationError.attributeTypeMap;
  }
}
