/**
 * MockServer API
 * Simple and fast mock server implemented in python
 *
 * The version of the OpenAPI document: 1.6.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "../api";

export class HttpRequest {
  /**
   * Http method
   */
  "method"?: string;
  /**
   * Url path
   */
  "path": string;
  /**
   * Query string parameters
   */
  "queryStringParameters"?: { [key: string]: Array<string> };

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: "method",
      baseName: "method",
      type: "string",
    },
    {
      name: "path",
      baseName: "path",
      type: "string",
    },
    {
      name: "queryStringParameters",
      baseName: "queryStringParameters",
      type: "{ [key: string]: Array<string>; }",
    },
  ];

  static getAttributeTypeMap() {
    return HttpRequest.attributeTypeMap;
  }
}
